// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhHXFet4W50R_VtmZo8wzP6_-faAV7RSU',
    appId: '1:1076398017483:web:5fae0dc2143ccb5eb6c44e',
    messagingSenderId: '1076398017483',
    projectId: 'aethera-2a620',
    authDomain: 'aethera-2a620.firebaseapp.com',
    storageBucket: 'aethera-2a620.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhHXFet4W50R_VtmZo8wzP6_-faAV7RSU',
    appId: '1:1076398017483:android:9c2d344e62f6e6c0b6c44e',
    messagingSenderId: '1076398017483',
    projectId: 'aethera-2a620',
    storageBucket: 'aethera-2a620.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhHXFet4W50R_VtmZo8wzP6_-faAV7RSU',
    appId: '1:1076398017483:ios:f5258df425d99280b6c44e',
    messagingSenderId: '1076398017483',
    projectId: 'aethera-2a620',
    storageBucket: 'aethera-2a620.firebasestorage.app',
    iosBundleId: 'com.aethera.aethera',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhHXFet4W50R_VtmZo8wzP6_-faAV7RSU',
    appId: '1:1076398017483:ios:f5258df425d99280b6c44e',
    messagingSenderId: '1076398017483',
    projectId: 'aethera-2a620',
    storageBucket: 'aethera-2a620.firebasestorage.app',
    iosBundleId: 'com.aethera.aethera',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhHXFet4W50R_VtmZo8wzP6_-faAV7RSU',
    appId: '1:1076398017483:web:760b4fab020984d6b6c44e',
    messagingSenderId: '1076398017483',
    projectId: 'aethera-2a620',
    authDomain: 'aethera-2a620.firebaseapp.com',
    storageBucket: 'aethera-2a620.firebasestorage.app',
  );
}
